### ISSUE TITLE
Support for zone status damper information

### ISSUE THREAD

**Issue by Aqualung812** [grivkees/homebridge-carrier-infinity#156]
I have a 4-zone system, and in one of those zones, the basement, I use a booster fan connected to a smart outlet. 

My goal is to make sure the booster fan only turns on when that zone is getting air delivered to it. 

I've attempted to use both the heating mode and fan status to do this, but it doesn't work completely because the Carrier system will not always be sending air to that zone based on those two statuses.

The idea solution would be to reference the "zone status" information that shows when that zone is heating or cooling. This is accessible in the Infinity module under Status, Temperature Control Status:
![IMG_0533](https://user-images.githubusercontent.com/90048888/150791637-2394ec3d-15c2-43d5-9029-d1f9ad2a7fea.PNG)

As you can see, with the above status, the basement is getting sent hot air, but nothing in the current plugin indicates this:
![image](https://user-images.githubusercontent.com/90048888/150791361-133fdc44-1c31-4ade-b28e-1096229bdbcb.png)

I'm not sure this information is available to you over API, so I get it if you can't implement this to do that limitation. 

The ideal solution would look at the damper status, which is found by holding down the service button and going to zone status:
![IMG_0534](https://user-images.githubusercontent.com/90048888/150791925-0a1734e2-74b1-4769-b028-badb9ced7bae.JPG)

This would allow fan speed to be based on damper position, with 0 being 0% fan speed, and 15 being 100%. 

Thank you!

**Comment by grivkees** [comment]
Hey! Thanks for writing this up!

It *should* show per zone heat/cool/off status, though I’m not sure how that fits in with the damper reported state.

I don’t have a multi zone system, so hard for me to tell. Can you follow the instructions below to share the system state?

https://github.com/grivkees/homebridge-carrier-infinity/wiki/Development#investigating-carrier-api-responses

Separately, it doesn’t look like HomeKit even exposes the cool/heat state as an automation trigger. So might need to just make a fake switch to do this anyway. Do you actually care about the damper % state? Or just whether it’s blowing or not in the zone?

**Comment by grivkees** [comment]
"zoneconditioning" in that paste is the state of the zone, and as far as I've seen can be idle/active_heat/active_cool. 

Do you have an example of where the system is fan_only and a damper is open (non-0)?

**Comment by Aqualung812** [comment]
It actually warmed up enough that the system already went into fan-only mode. Technically the heat is enabled, but all zones are warm enough that no heat is active. So the Upstairs, Suite, and Main Floor all are showing "idle" on conditioning but non-zero dampers.

`<status version="1.48" xmlns:atom="http://www.w3.org/2005/Atom"><atom:link rel="self" href="https://www.app-api.ing.carrier.com/systems/5219W100803/status"/><atom:link rel="http://www.api.ing.carrier.com/rels/system" href="https://www.app-api.ing.carrier.com/systems/5219W100803"/><timestamp>2022-02-15T19:18:50.156Z</timestamp><pingRate>15</pingRate><iduStatusPingRate>93600</iduStatusPingRate><iduFaultsPingRate>86400</iduFaultsPingRate><oduStatusPingRate>90000</oduStatusPingRate><oduFaultsPingRate>82800</oduFaultsPingRate><historyPingRate>75600</historyPingRate><equipEventsPingRate>79200</equipEventsPingRate><rootCausePingRate>72000</rootCausePingRate><serverHasChanges>false</serverHasChanges><configHasChanges>false</configHasChanges><dealerHasChanges>false</dealerHasChanges><dealerLogoHasChanges>false</dealerLogoHasChanges><oduConfigHasChanges>false</oduConfigHasChanges><iduConfigHasChanges>false</iduConfigHasChanges><utilityEventsHasChanges>false</utilityEventsHasChanges><sensorConfigHasChanges>false</sensorConfigHasChanges><sensorProfileHasChanges>false</sensorProfileHasChanges><sensorDiagnosticHasChanges>false</sensorDiagnosticHasChanges><name>2800 HVAC</name><oat>49</oat><mode>gasheat</mode><cfgem>C</cfgem><cfgtype>heatcool</cfgtype><vacatrunning>off</vacatrunning><filtrlvl>100</filtrlvl><uvlvl>100</uvlvl><humlvl>100</humlvl><ventlvl>100</ventlvl><humid>off</humid><vent/><localTime>2022-02-15T14:18:50.156</localTime><oprstsmsg/><isDisconnected>false</isDisconnected><idu><type>furnace2stg</type><opstat>off</opstat><cfm>636</cfm></idu><odu><type>proteushp</type><opstat>off</opstat><opmode>off</opmode></odu><zones><zone id="1"><name>Upstairs</name><enabled>on</enabled><currentActivity>home</currentActivity><rt>21.5</rt><rh>30</rh><fan>low</fan><hold>off</hold><htsp>19.0</htsp><clsp>23.0</clsp><otmr>00:00</otmr><zoneconditioning>idle</zoneconditioning><damperposition>10</damperposition><occupancy/><occupancyOverride>off</occupancyOverride></zone><zone id="2"><name>Suite</name><enabled>on</enabled><currentActivity>wake</currentActivity><rt>23.5</rt><rh>30</rh><fan>med</fan><hold>off</hold><htsp>23.5</htsp><clsp>26.5</clsp><otmr>00:00</otmr><zoneconditioning>idle</zoneconditioning><damperposition>15</damperposition><occupancy/><occupancyOverride>off</occupancyOverride></zone><zone id="3"><name>Main Floor</name><enabled>on</enabled><currentActivity>home</currentActivity><rt>20.0</rt><rh>30</rh><fan>med</fan><hold>off</hold><htsp>20.0</htsp><clsp>24.0</clsp><otmr>00:00</otmr><zoneconditioning>idle</zoneconditioning><damperposition>14</damperposition><occupancy/><occupancyOverride>off</occupancyOverride></zone><zone id="4"><name>Basement</name><enabled>on</enabled><currentActivity>away</currentActivity><rt>12.5</rt><rh>30</rh><fan>off</fan><hold>on</hold><htsp>10.0</htsp><clsp>29.0</clsp><otmr>00:00</otmr><zoneconditioning>idle</zoneconditioning><damperposition>0</damperposition><occupancy/><occupancyOverride>off</occupancyOverride></zone><zone id="5"><name>Zone 5</name><enabled>off</enabled><currentActivity>away</currentActivity><rt/><rh>30</rh><fan>off</fan><hold>off</hold><htsp>15.5</htsp><clsp>26.5</clsp><otmr>00:00</otmr><zoneconditioning>idle</zoneconditioning><damperposition>0</damperposition><occupancy/><occupancyOverride>off</occupancyOverride></zone><zone id="6"><name>Zone 6</name><enabled>off</enabled><currentActivity>away</currentActivity><rt/><rh>30</rh><fan>off</fan><hold>off</hold><htsp>15.5</htsp><clsp>26.5</clsp><otmr>00:00</otmr><zoneconditioning>idle</zoneconditioning><damperposition>0</damperposition><occupancy/><occupancyOverride>off</occupancyOverride></zone><zone id="7"><name>Zone 7</name><enabled>off</enabled><currentActivity>away</currentActivity><rt/><rh>30</rh><fan>off</fan><hold>off</hold><htsp>15.5</htsp><clsp>26.5</clsp><otmr>00:00</otmr><zoneconditioning>idle</zoneconditioning><damperposition>0</damperposition><occupancy/><occupancyOverride>off</occupancyOverride></zone><zone id="8"><name>Zone 8</name><enabled>off</enabled><currentActivity>away</currentActivity><rt/><rh>30</rh><fan>off</fan><hold>off</hold><htsp>15.5</htsp><clsp>26.5</clsp><otmr>00:00</otmr><zoneconditioning>idle</zoneconditioning><damperposition>0</damperposition><occupancy/><occupancyOverride>off</occupancyOverride></zone></zones></status>`

**Comment by grivkees** [comment]
Awesome, thats perfect. Thanks!
I'll take a closer look and let you know if I have any other questions.

**Comment by etomnash** [comment]
To chime in: I have used the accessory HTTP SWITCH to set Zone Condition cooling and heating state switches for each of my 2 zones via http calls to a local .php site. In the php code I access Infinitude status and decode the json to get the state. (See below). I then use the switch in HomeKit for automations. 

It would be nice, of course, if this (very nice) homebridge plug-in could set switches for heating and cooling in each zone. 

However, I would still have to use this php path for the automations I want. Mainly what I am doing is comparing indoor and outdoor temperature and triggering a notification if, for example, the cooling is on when the outside temperature is cooler than inside. The notification asks for the door/window to be opened by anyone who is home. The notification goes via the iOS app pushcut. This whole process is quite heroic, but works, and is necessitated by the fact that HomeKit does not allow for automations based on comparison of temperatures (believe it or not.)

Here's an example of the php code, here setting the switch for downstairs cooling: 

<?php

$json = file_get_contents("http://172.16.1.57:3000/api/status/zones/");
$jsondec = (json_decode($json, true));
$json = file_get_contents("http://172.16.1.57:3000/api/status");
$gardendec  = (json_decode($json, true));

$upstairs = $jsondec["zones"]["zone"][0]["rt"][0];
$dnstairs = $jsondec["zones"]["zone"][1]["rt"][0];
$upcoolheat = $jsondec["zones"]["zone"][0]["zoneconditioning"][0];
$dncoolheat = $jsondec["zones"]["zone"][1]["zoneconditioning"][0];

if (strpos( $dncoolheat,"cool" )!== false) {
  echo "true" ;
  } else {
  echo "false";
}

$garden = $gardendec["oat"][0];

$dnhotoutside = ($garden > $dnstairs);
$upcooloutside = $garden < $upstairs;

?>

The code for comparisons of indoor/outdoor temps is more complicated because it has to have timers and a cache to deal with a Davis Weather Station api that provides garbage if hit too often.

**Comment by grivkees** [comment]
@Aqualung812
The fan currently only shows as 'active' when the fan is in an explicit low/med/high setting. It does not show as blowing when the fan is set to auto and the system is active. I think I'm ok with having the fan display as blowing anytime air is moving through the zone, but need to think on how to show it a bit more. (I can't really show how fast the fan is blowing when set to auto in a way that wouldn't be confusing in homekit). Then, since you can automate based on an active fan, you should be able to get the other fan working.

Also, if you see the situation where the basement is getting hot air, but homekit dosen't show that thermostat as heating, see if you can try to capture a status output. That is just a bug, but not sure how its happening.

**Comment by grivkees** [comment]
@etomnash that is indeed a heroic automation. 

I'd be curious if you could use an [ios shortcut](https://support.apple.com/guide/shortcuts/welcome/ios) to do that logic and notification. It seems to have if/else, ways to get weather and homekit status, and ways to take homekit actions. There doesn't seem to be a native way to run a shortcut continuously, or even have it trigger on its own like HK automations, but there do seem to be some hacks to run the check every min.

**Comment by etomnash** [comment]
Its been a while since I immersed myself in this...

Looking at it now, I think I might be able to do json decoding in the HomeKit scripting using the Library capability, then set however many temperature Variables needed, and then use If/Then compares on them. I would still need to use the iOS app pushcart for notifications as HomeKit scripting does not allow for that (Shortcuts does). 

The other issue I am not sure I could handle in HomeKit scripting is protecting outside servers like Davis Weather Station, Carrier or Infinitude from getting hammered too often and providing error codes or garbage.  I do some caching in php now. Maybe HomeKit would handle this correctly, or I could use waits, etc. to do so - probably, but I'm not sure.

As for doing this in iOS Shortcuts, the problem is you need a trigger. Trigger options include HomeKit accessories, but only On/Off switches, not variables like temperatures. Somewhere you have to create an accessory that is a switch with a state based on multiple temperatures. I don't think you can create an accessory in HomeKit scripting as it assumes accessories exist. Also not possible AFAIK in Homebridge with existing plugins. So back to a .php server or HomeKit Library json decoding, if that can be made to work with outside servers....

I ended up in .php because at the time I didn't understand the Library capability allows json decoding - and I was just starting with json. One retrospective advantage about php is that it is a lot easier to read and code a text-like php file than the HomeKit or Shortcuts scripting GUI. Disadvantage is you have to read the php manuals...

I would be interested if someone sees another way to do this sort of thing.

**Comment by etomnash** [comment]
Looking at Shortcuts a bit more. The Shortcuts app allows for 2 kinds of automation: Home and Personal. With home automations you can trigger on accessories that are switch-like, and the list of scripting options and the GUI is just the same as in HomeKit. So there is no Notification option, which is why PushCut exists. With personal automations you cannot trigger on accessories, but you can fire notifications. The home automations run on a HomeKit server like an AppleTV that is always on. The personal automations run on a single iOS device, which may not be at home or on. I can't see any reason why home automations can't support notifications, but maybe there is one. I also see no reason why the scripting couldn't support trigger access to conditions on multiple accessory variables like temperature.

**Comment by Aqualung812** [comment]
Here it is in basically the same state as my first post:

`<status version="1.48" xmlns:atom="http://www.w3.org/2005/Atom"><atom:link rel="self" href="https://www.app-api.ing.carrier.com/systems/snip/status"/><atom:link rel="http://www.api.ing.carrier.com/rels/system" href="https://www.app-api.ing.carrier.com/systems/snip"/><timestamp>2022-03-09T20:43:27.088Z</timestamp><pingRate>15</pingRate><iduStatusPingRate>93600</iduStatusPingRate><iduFaultsPingRate>86400</iduFaultsPingRate><oduStatusPingRate>90000</oduStatusPingRate><oduFaultsPingRate>82800</oduFaultsPingRate><historyPingRate>75600</historyPingRate><equipEventsPingRate>79200</equipEventsPingRate><rootCausePingRate>72000</rootCausePingRate><serverHasChanges>false</serverHasChanges><configHasChanges>false</configHasChanges><dealerHasChanges>false</dealerHasChanges><dealerLogoHasChanges>false</dealerLogoHasChanges><oduConfigHasChanges>false</oduConfigHasChanges><iduConfigHasChanges>false</iduConfigHasChanges><utilityEventsHasChanges>false</utilityEventsHasChanges><sensorConfigHasChanges>false</sensorConfigHasChanges><sensorProfileHasChanges>false</sensorProfileHasChanges><sensorDiagnosticHasChanges>false</sensorDiagnosticHasChanges><name>2800 HVAC</name><oat>51</oat><mode>off</mode><cfgem>C</cfgem><cfgtype>heatcool</cfgtype><vacatrunning>off</vacatrunning><filtrlvl>17</filtrlvl><uvlvl>100</uvlvl><humlvl>100</humlvl><ventlvl>100</ventlvl><humid>off</humid><vent/><localTime>2022-03-09T15:43:27.088</localTime><oprstsmsg/><isDisconnected>false</isDisconnected><idu><type>furnace2stg</type><opstat>off</opstat><cfm>563</cfm></idu><odu><type>proteushp</type><opstat>off</opstat><opmode>off</opmode></odu><zones><zone id="1"><name>Upstairs</name><enabled>on</enabled><currentActivity>home</currentActivity><rt>22.0</rt><rh>38</rh><fan>low</fan><hold>off</hold><htsp>19.0</htsp><clsp>23.0</clsp><otmr>00:00</otmr><zoneconditioning>idle</zoneconditioning><damperposition>10</damperposition><occupancy/><occupancyOverride>off</occupancyOverride></zone><zone id="2"><name>Suite</name><enabled>on</enabled><currentActivity>home</currentActivity><rt>23.0</rt><rh>38</rh><fan>low</fan><hold>off</hold><htsp>20.0</htsp><clsp>24.0</clsp><otmr>00:00</otmr><zoneconditioning>idle</zoneconditioning><damperposition>10</damperposition><occupancy/><occupancyOverride>off</occupancyOverride></zone><zone id="3"><name>Main Floor</name><enabled>on</enabled><currentActivity>home</currentActivity><rt>20.0</rt><rh>38</rh><fan>med</fan><hold>off</hold><htsp>20.0</htsp><clsp>24.0</clsp><otmr>00:00</otmr><zoneconditioning>idle</zoneconditioning><damperposition>15</damperposition><occupancy/><occupancyOverride>off</occupancyOverride></zone><zone id="4"><name>Basement</name><enabled>on</enabled><currentActivity>away</currentActivity><rt>15.5</rt><rh>38</rh><fan>off</fan><hold>off</hold><htsp>10.0</htsp><clsp>29.0</clsp><otmr>00:00</otmr><zoneconditioning>idle</zoneconditioning><damperposition>0</damperposition><occupancy/><occupancyOverride>off</occupancyOverride></zone><zone id="5"><name>Zone 5</name><enabled>off</enabled><currentActivity>home</currentActivity><rt/><rh>38</rh><fan>off</fan><hold>off</hold><htsp>20.0</htsp><clsp>24.5</clsp><otmr>00:00</otmr><zoneconditioning>idle</zoneconditioning><damperposition>0</damperposition><occupancy>occupied</occupancy><occupancyOverride>on</occupancyOverride></zone><zone id="6"><name>Zone 6</name><enabled>off</enabled><currentActivity>home</currentActivity><rt/><rh>38</rh><fan>off</fan><hold>off</hold><htsp>20.0</htsp><clsp>24.5</clsp><otmr>00:00</otmr><zoneconditioning>idle</zoneconditioning><damperposition>0</damperposition><occupancy>occupied</occupancy><occupancyOverride>on</occupancyOverride></zone><zone id="7"><name>Zone 7</name><enabled>off</enabled><currentActivity>home</currentActivity><rt/><rh>38</rh><fan>off</fan><hold>off</hold><htsp>20.0</htsp><clsp>24.5</clsp><otmr>00:00</otmr><zoneconditioning>idle</zoneconditioning><damperposition>0</damperposition><occupancy>occupied</occupancy><occupancyOverride>on</occupancyOverride></zone><zone id="8"><name>Zone 8</name><enabled>off</enabled><currentActivity>home</currentActivity><rt/><rh>38</rh><fan>off</fan><hold>off</hold><htsp>20.0</htsp><clsp>24.5</clsp><otmr>00:00</otmr><zoneconditioning>idle</zoneconditioning><damperposition>0</damperposition><occupancy>occupied</occupancy><occupancyOverride>on</occupancyOverride></zone></zones></status>`

**Comment by grivkees** [comment]
@Aqualung812 Ah, prep_heat is what I was missing here. Awesome. Fixing it so it gives a better error as well if theres any others I'm missing like this, so hopefully this is clearer if theres another one of these.

**Comment by grivkees** [comment]
@Aqualung812 I think the version that pushes on @next from this commit should fix the issues. If not, please reopen the issue and I'll take another look.

**Comment by Aqualung812** [comment]
This didn't solve the exact issue, I'm sorry.

Right now, my downstairs is getting heat delivered and the damper for it is open. My suite is also set to heat and have the fan on, but it is not in the active heat state since it is warm enough in there, and doesn't have its damper open.

It shows the fan as active at 33% in HomeKit in the Suite, even though no air is actually be sent there. I think that is because the fan is still based on the auto/high/med/low setting, not the damper setting. Is that right?

**Comment by grivkees** [comment]
Can you send a picture of what you see?

There is a difference between the currently configured speed, which it sounds like you do have as low/33%. And how it shows the “active state”, which would be off here. HomeKit should show the fan as “off”, but the speed setting will still show as 33%. (This generally looks like a non spinning fan in the UI, as opposed to a spinning fan. And the thermostats will not show “all on” on its tile)

**Comment by Aqualung812** [comment]
![078495C0-80AF-4960-8D15-AE6A7B478839](https://user-images.githubusercontent.com/90048888/159141835-8f019ba7-e23d-4656-a8d1-e92d0a7e6da0.jpeg)
![EB4D4023-7B92-4620-8772-DCD2B00BD1FA](https://user-images.githubusercontent.com/90048888/159141836-e315e4d9-600c-487c-882e-0abc4ff7cac3.png)
![5B89ACD8-3CED-4D1E-8CEC-BC2FE42E9078](https://user-images.githubusercontent.com/90048888/159141837-1a91032b-fb21-4e08-a845-4fd0a707fa77.jpeg)

Currently, the Upstairs (aka hallway) is not getting air, but the fan shows on.

**Comment by grivkees** [comment]
Can you share the status api output while this is occurring?

**Comment by grivkees** [comment]
Actually no need. I think I know what it is.

**Comment by grivkees** [comment]
I _think_ that will do it. I finally gave up and took the damper into account 😄 

New build should be ready in the next few min. Let me know if that does it or not.

**Comment by Aqualung812** [comment]
![F82DAAEF-8A03-414E-9823-20598F4DB179](https://user-images.githubusercontent.com/90048888/159145146-56005f76-3236-4bee-88d2-d0d8a2400353.jpeg)
![1343E2AF-4123-4101-8A8A-5698956A9E91](https://user-images.githubusercontent.com/90048888/159145147-ea24a5a1-3f37-4a0d-962d-c320aa64b5b4.jpeg)

That did it! You can see how the Upstairs and Suite fans now show off when the main floor kicked on and called for heat, and the dampers closed for those two zones so only the main floor is getting air. 

One it hit the set point, the fan, which was set to auto on main floor, correctly went to off and the other two showed on, on low as matches the actual state.

**Comment by grivkees** [comment]
Made a few more changes. If the system is off, the fan will definitely show off now.
I did also make a change to make setting the fan speed from homekit appear to stick better while the updates push to the thermostat. This will still take into account the damper being closed though. But let me know if you see any issues with it.

**Comment by Aqualung812** [comment]
Looks good so far!
